env = XCURSOR_THEME,Imouto
env = XCURSOR_SIZE,32
env = HYPRCURSOR_THEME,Imouto
env = HYPRCURSOR_SIZE,32

env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_STYLE_OVERRIDE,kvantum
env = SDL_VIDEODRIVER,wayland
env = MOZ_ENABLE_WAYLAND,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = OZONE_PLATFORM,wayland
# Dialogues natifs (VS Code / Electron) via XDG Desktop Portal (Yazi + termfilechooser)
env = GTK_USE_PORTAL,1

xwayland {
  force_zero_scaling = true
}

ecosystem {
  no_update_news = true
}

